catalog:
  unocss: ^0.0.0

catalogs:
  framework:
    nuxt: ^4.1.1
    sass-embedded: ^1.92.1
    vue: ^3.5.21
    vue-router: ^4.5.1
  quality:
    '@antfu/eslint-config': ^5.3.0
    '@zinkawaii/stylelint-config': 0.3.3
    eslint: ^9.35.0
    stylelint: ^16.24.0
  ui:
    '@iconify-json/logos': ^1.2.9
    '@iconify-json/ri': ^1.2.5
    '@nuxt/icon': ^2.0.0
    '@unocss/nuxt': ^66.5.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

shamefullyHoist: true
