catalog:
  unocss: ^0.0.0

catalogs:
  framework:
    nuxt: ^4.0.3
    sass-embedded: ^1.91.0
    vue: ^3.5.20
    vue-router: ^4.5.1
  quality:
    '@antfu/eslint-config': ^5.2.1
    '@zinkawaii/stylelint-config': 0.3.3
    eslint: ^9.34.0
    stylelint: ^16.23.1
  ui:
    '@iconify-json/logos': ^1.2.9
    '@iconify-json/ri': ^1.2.5
    '@nuxt/icon': ^2.0.0
    '@unocss/nuxt': ^66.5.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

shamefullyHoist: true
