catalog:
  '@antfu/eslint-config': ^4.18.0
  '@iconify-json/logos': ^1.2.5
  '@iconify-json/ri': ^1.2.5
  '@nuxt/icon': ^1.15.0
  '@unocss/nuxt': ^66.3.3
  '@zinkawaii/stylelint-config': 0.3.3
  eslint: ^9.31.0
  nuxt: ^4.0.1
  sass-embedded: ^1.89.2
  unocss: ^66.3.3
  vue: ^3.5.18
  vue-router: ^4.5.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

shamefullyHoist: true
