// @keep-sorted
const techMap = {
    Axios: "simple-icons:axios",
    Bun: "logos:bun",
    CentOS: "devicon:centos",
    Consul: "logos:consul",
    Docker: "logos:docker-icon",
    Electron: "file-icons:electron",
    Ent: "simple-icons:entity",
    Gin: "logos:gin",
    Gitea: "simple-icons:gitea",
    GitHub: "akar-icons:github-fill",
    Gitlab: "devicon:gitlab",
    Go: "vscode-icons:file-type-go",
    Gorm: "simple-icons:go",
    Grafana: "devicon:grafana",
    gRPC: "logos:grpc",
    Harbor: "devicon:harbor",
    "Hyper-V": "devicon:hyperv",
    iKuai: "mi:switch",
    Jaeger: "devicon:jaegertracing",
    Jenkins: "vscode-icons:file-type-jenkins",
    Kratos: "custom:kratos",
    Kubernetes: "logos:kubernetes",
    Linux: "logos:linux-tux",
    NaiveUI: "logos:naiveui",
    Nitro: "unjs:nitro",
    Nuxt: "vscode-icons:file-type-nuxt",
    OpenTelemetry: "devicon:opentelemetry",
    Pinia: "logos:pinia",
    Prometheus: "devicon:prometheus",
    Protobuf: "catppuccin:proto",
    Scss: "vscode-icons:file-type-scss",
    Server: "uil:server",
    TypeScript: "vscode-icons:file-type-typescript-official",
    Ubuntu: "logos:ubuntu",
    UnoCSS: "logos:unocss",
    Vite: "logos:vitejs",
    VitePress: "simple-icons:vitepress",
    "Vue 3": "logos:vue",
    VueUse: "logos:vueuse",
    Wire: "simple-icons:wire",
};

export type Tech = keyof typeof techMap;

export const getTechIcon = (tech: Tech) => techMap[tech] || "ri:code-line";
